language: node_js
node_js:
  - "lts/*"
script:
  - npx flow check --max-warnings 0
  - npm run build
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: build/
  on:
    branch: master